#!/bin/bash
# Generate Version.swift from Version.json

set -e

VERSION_FILE="Version.json"
OUTPUT_FILE="Sources/MacWindowDiscovery/Core/Version.swift"

# Check if Version.json exists
if [ ! -f "$VERSION_FILE" ]; then
    echo "Error: $VERSION_FILE not found"
    exit 1
fi

# Read version and build number
version=$(grep -o '"version":[[:space:]]*"[^"]*"' "$VERSION_FILE" | grep -o '[0-9]*\.[0-9]*\.[0-9]*')
build=$(grep -o '"build":[[:space:]]*[0-9]*' "$VERSION_FILE" | grep -o '[0-9]*')

# Parse version components
IFS='.' read -r major minor patch <<< "$version"

# Generate Swift file
cat > "$OUTPUT_FILE" << EOF
// Generated file - DO NOT EDIT
// This file is automatically generated from Version.json
// To update version, modify Version.json and run: make generate-version

import Foundation

/// Version information for MacWindowDiscovery
public struct Version {
    /// Major version number
    public static let major: Int = $major

    /// Minor version number
    public static let minor: Int = $minor

    /// Patch version number
    public static let patch: Int = $patch

    /// Build number (increments with each build)
    public static let build: Int = $build

    /// Full version string (e.g., "1.0.0")
    public static let string: String = "$version"

    /// Full version with build number (e.g., "1.0.0 (42)")
    public static let fullString: String = "$version ($build)"

    /// Short version for display (e.g., "v1.0.0")
    public static let short: String = "v$version"
}
EOF

echo "Generated $OUTPUT_FILE"
echo "  Version: $version"
echo "  Build: $build"
