// Generated file - DO NOT EDIT
// This file is automatically generated from Version.json
// To update version, modify Version.json and run: make generate-version

import Foundation

/// Version information for MacWindowDiscovery
public struct Version {
    /// Major version number
    public static let major: Int = 0

    /// Minor version number
    public static let minor: Int = 5

    /// Patch version number
    public static let patch: Int = 0

    /// Build number (increments with each build)
    public static let build: Int = 1

    /// Full version string (e.g., "1.0.0")
    public static let string: String = "0.5.0"

    /// Full version with build number (e.g., "1.0.0 (42)")
    public static let fullString: String = "0.5.0 (1)"

    /// Short version for display (e.g., "v1.0.0")
    public static let short: String = "v0.5.0"
}
